version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # THIS MAKES SURE DOCKER LOOKS AT NODE_MODULES IN THE CONTAINER NOT ON THE COMPUTER
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # THIS MAKES SURE DOCKER LOOKS AT NODE_MODULES IN THE CONTAINER NOT ON THE COMPUTER
      - .:/app
    command: ["npm", "run", "test"]